### ISSUE TITLE
Build tags for Java 11 for GraalVM 19.3.0 docker images (not just for Java 8)

### ISSUE THREAD

**Issue by neomatrix369** [findepi/graalvm-docker#1]
By this I mean, although this repo has been doing a fantastic job of creating Docker images with the GraalVM binaries of various types in it till now (see https://hub.docker.com/r/findepi/graalvm).

Since 19.3.0, things have changed, GraalVM now supports Java 11 (not just Java 8) and so every release will have artifacts for Java 11 as well, see https://github.com/graalvm/graalvm-ce-builds/releases/tag/vm-19.3.0 (previously releases could be found at https://github.com/oracle/graal/releases).

Which means the graalvm releases on Docker hub should also contain the tags for Java 11 as well, i.e. `findepi/graalvm:19.3.0-xxx-java-11`

Existing tags which are Java 8 inherently will have to get a new name, i.e.  `findepi/graalvm:19.3.0-xxx-java-8`.

where `-xxx-` represents things like `all`, `polyglot`, etc...

_PS: Wow! The first issue on this repo! Raising this issue after a conversation on twitter see https://twitter.com/theNeomatrix369/status/1197699688750866432._

**Comment by findepi** [comment]
@neomatrix369 thanks!
