### ISSUE TITLE
missing library for native-image on "findepi/graalvm:20.3.0-java11-native"

### ISSUE THREAD

**Issue by BrunoBonacci** [findepi/graalvm-docker#4]
trying to build a native image using `findepi/graalvm:20.3.0-java11-native` but i get the following error.

```
/usr/bin/ld: cannot find -lstdc++
collect2: error: ld returned 1 exit status
```
it looks like the standard c++ library is missing.

please add this to the base image.
```
 apt-get install -y g++
```

**Comment by findepi** [comment]
@BrunoBonacci thanks for the report!



> please add this to the base image.
> 
> ```
>  apt-get install -y g++
> ```

would you like to take the privilege of making a PR for this?
